### ISSUE TITLE
data augmentation for breast cancer

### ISSUE THREAD

**Issue by martinkremnicky** [martinkremnicky/TUe_ITP_healthcare_group_2#42]
- [x] elongation in y
- [x] saving frames
- [x] showing animation
- [x] blur
- [x] single .jpg prototype
- [x] stable image size fix
- [x] elongation in x
- [x] randomization of parameters
- [x] code reformatting
- [x] reading .nii.gz
- [x] (correctly) augmenting .nii.gz
- [x] saving .nii.gz  
- [ ] user friendly
- [x] add segmentation augmentation
- [ ] add folder compartmentalization (according to agreed folder structure)

**Comment by hkerkhoven** [comment]
@martinkremnicky I just saw that this issue is still open. Are you still working on this or did you forget to close it? I was wondering since we didn't talk about this during the meeting when we updated on our tasks.

**Comment by martinkremnicky** [comment]
@hkerkhoven yes, I'm still working on this.

**Comment by martinkremnicky** [comment]
Practically finished, working on making it more user friendly and streamlined

**Comment by martinkremnicky** [comment]
I'd say I'm done, finished with fee2a570e1b593560622d8d88d79f3a4b96afe0e. Just make sure you run `augmentation.ipynb` and not `test_augmentation.ipynb`, as the latter contains W.I.P. code
