### ISSUE TITLE
write about sample size in report

### ISSUE THREAD

**Issue by martinkremnicky** [martinkremnicky/TUe_ITP_healthcare_group_2#44]
since we're now dealing with breast cancer as opposed to lung cancer, 309 is outdated

Edit from meeting (24/4/24):
Since we have calculated the size again we will have to explain this in the report as well, therefore this task now includes writing about sample size in the report. Therefore I will also change the title, since the sample size has already been calculated.

**Comment by hkerkhoven** [comment]
On Hold until the outline of the report has been made

**Comment by hkerkhoven** [comment]
For now I wrote a small part on the sample size, since we do not have a lot of space I am keeping it short. We can always change it.
