### ISSUE TITLE
upload data augmentation to GitHub

### ISSUE THREAD

**Issue by hkerkhoven** [martinkremnicky/TUe_ITP_healthcare_group_2#50]
make sure the algorithms are available for everyone so that everyone can contribute and see what is happening. This we will do by uploading the algorithms to github.

**Comment by martinkremnicky** [comment]
@hkerkhoven done, _however_, let's discuss the GitHub strategy on Wednesday. 
In short:
- consider `dev` the new `main`
- _**never push to `main`**_. Consider this as our production branch, and should only be merged into by `dev`, at the end of the course.
- when uploading code for a new feature, make a new branch
- when you think you're finished with the feature you're adding, make a PR to `dev`, and one other person will have to approve it

This strategy concerns everyone, so @thernansab04 @cmichalopoulos2 please read.

**Comment by hkerkhoven** [comment]
I don't exactly get your point, so I'll add it to the agenda. I think you just explained the normal git rules but am not sure, so we'll talk about this today.
