### ISSUE TITLE
message UMCU

### ISSUE THREAD

**Issue by hkerkhoven** [martinkremnicky/TUe_ITP_healthcare_group_2#59]

**Comment by martinkremnicky** [comment]
"Found it: https://www.umcutrecht.nl/en/research/researchers/monninkhof-em
More lifestyle in connection with cancer, but I'm sure she can forward you to the right people.
There is also a list of more cancer researchers at UMCU here: https://juliuscentrum.umcutrecht.nl/en/cancer "

This is the message I got from my colleague.

**Comment by hkerkhoven** [comment]
Messaged researcher Monninkhof
