### ISSUE TITLE
Correct Radiation Reduction

### ISSUE THREAD

**Issue by hkerkhoven** [martinkremnicky/TUe_ITP_healthcare_group_2#62]
Recalculate and correct the radiation reduction that is used in the midterm presentation slides to a better estimate.

**Comment by martinkremnicky** [comment]
_Stemming from "Dosimetric evaluation of respiratory gating on a 0.35-T magnetic resonance–guided radiotherapy linac" by Charters et al._



![Image](https://github.com/martinkremnicky/TUe_ITP_healthcare_group_2/assets/94135385/3fd8e47f-ac2c-4ffc-94bb-e081cfb2ecf3)

If we can close the gap between 4 fps and 8 fps (highlighted in pink), we can get anywhere from 17% (from 69 to 81) to 120% (from 20 to 44) increase in precision of planned dose delivery.

**Comment by hkerkhoven** [comment]
@martinkremnicky I do not understand where the percentages come from. Do you have a file for this so I can read it somewhere?

**Comment by martinkremnicky** [comment]
@hkerkhoven so, as I said in the comment, closing the gap from 69 to 81 would be around a 17% increase in precision. I calculated this by dividing 81 (new performance value, if we manage to get there) by 69 (old performance). Thus, 81/69 = 1.17, so 17% more than the original. Same thing for 44/20, which is 2.20, translating to a 120% increase.
